name: 中文测试啊啊啊对对对
description: 中文测试啊啊啊对对对
#title: 你的标题
labels:
  - enhancement
  - question
assignees:
  - Arondight
body:
  - type: textarea
    id: question
    attributes:
      label: 中文测试啊啊啊对对对
      description: 中文测试啊啊啊对对对
      #placeholder:
      #value:
    validations:
      required: true
  - type: textarea
    id: git-log
    attributes:
      label: 中文测试啊啊啊对对对
      description: 中文测试啊啊啊对对对
      render: Text
      #placeholder:
    validations:
      required: false
