# 圣遗物部位权值 ( 生之花 / 死之羽 / 时之沙 / 空之杯 / 理之冠 )
# 圣遗物主属性权值 ( HP, HP%, DEF, DEF%, ER%, EM, ATK, ATK%, CRIT DMG%, CRIT Rate%, Physical%, Anemo%, Cryo%, Electro%, Geo%, Hydro%, Pyro%, Healing% )
weights:
  - [ 214, 214, 208, 182, 182 ]                                                                    # 套装部位
  - [ 108, 108, 108, 108, 104, 104, 102, 102,  78,  78,   0,   0,   0,   0,   0,   0,   0,   0 ]   # 副词条
  - [   0, 247,   0, 247, 132, 132,   0, 242,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0 ]   # 时之沙
  - [   0, 227,   0, 227,   0, 117,   0, 212,   0,   0,  31,  31,  31,  31,  31,  31,  31,   0 ]   # 空之杯
  - [   0, 209,   0, 209,   0, 117,   0, 198,  96,  96,   0,   0,   0,   0,   0,   0,   0,  75 ]   # 理之冠
  - [ 720, 280 ]                                                                                   # 初始(决定初始词条个数)
  - [ 235, 245, 255, 265 ]                                                                         # 档位(决定数值大小)

# 圣遗物副属性权值 ( HP, HP%, DEF, DEF%, ER%, EM, ATK, ATK%, CRIT DMG%, CRIT Rate% )
# 数据参考: https://wiki.biligame.com/ys/%E5%85%B3%E4%BA%8E%E5%9C%A3%E9%81%97%E7%89%A9%E9%9A%90%E8%97%8F%E5%B0%8F%E6%95%B0%E7%9A%84%E7%A0%94%E7%A9%B6
values:
  - [ 298.75, 0.0583, 23.15, 0.0729, 0.0648, 23.31, 19.45, 0.0583, 0.0777, 0.0389 ]   # 一档
  - [ 268.88, 0.0525, 20.83, 0.0656, 0.0583, 20.98, 17.51, 0.0525, 0.0699, 0.0350 ]   # 二挡
  - [ 239.00, 0.0466, 18.52, 0.0583, 0.0518, 18.65, 15.56, 0.0466, 0.0622, 0.0311 ]   # 三档
  - [ 209.13, 0.0408, 16.20, 0.0510, 0.0453, 16.32, 13.62, 0.0408, 0.0544, 0.0272 ]   # 四档

artifacts:
  -
    id: 0
    maxRarity: 5
    mainName: "悠古的磐岩"
    subName: [ "盘陀裂生之花", "嵯峨群峰之翼", "星罗圭壁之晷", "巉岩琢塑之樽", "不动玄石之相" ]
  -
    id: 1
    maxRarity: 5
    mainName: "冰风迷途的勇士"
    subName: [ "历经风雪的思念", "摧冰而行的执望", "冰雪故园的终期", "遍结寒霜的傲骨", "破冰踏雪的回音" ]
  -
    id: 2
    maxRarity: 5
    mainName: "染血的骑士道"
    subName: [ "染血的铁之心", "染血的黑之羽", "染血骑士之时", "染血骑士之杯", "染血的铁假面" ]
  -
    id: 3
    maxRarity: 5
    mainName: "炽烈的炎之魔女"
    subName: [ "魔女的炎之花", "魔女常燃之羽", "魔女破灭之时", "魔女的心之火", "焦灼的魔女帽" ]
  -
    id: 4
    maxRarity: 5
    mainName: "角斗士的终幕礼"
    subName: [ "角斗士的留恋", "角斗士的归宿", "角斗士的希冀", "角斗士的酣醉", "角斗士的凯旋" ]
  -
    id: 5
    maxRarity: 5
    mainName: "沉沦之心"
    subName: [ "饰金胸花", "追忆之风", "坚铜罗盘", "沉波之盏", "酒渍船帽" ]
  -
    id: 6
    maxRarity: 5
    mainName: "渡过烈火的贤人"
    subName: [ "渡火者的决绝", "渡火者的解脱", "渡火者的煎熬", "渡火者的醒悟", "渡火者的智慧" ]
  -
    id: 7
    maxRarity: 5
    mainName: "被怜爱的少女"
    subName: [ "远方的少女之心", "少女飘摇的思念", "少女苦短的良辰", "少女片刻的闲暇", "少女易逝的芳颜" ]
  -
    id: 8
    maxRarity: 5
    mainName: "昔日宗室之仪"
    subName: [ "宗室之花", "宗室之翎", "宗室时计", "宗室银瓮", "宗室面具" ]
  -
    id: 9
    maxRarity: 5
    mainName: "逆飞的流星"
    subName: [ "夏祭之花", "夏祭终末", "夏祭之刻", "夏祭水玉", "夏祭之面" ]
  -
    id: 10
    maxRarity: 5
    mainName: "如雷的盛怒"
    subName: [ "雷鸟的怜悯", "雷灾的孑遗", "雷霆的时计", "降雷的凶兆", "唤雷的头冠" ]
  -
    id: 11
    maxRarity: 5
    mainName: "平息鸣雷的尊者"
    subName: [ "平雷之心", "平雷之羽", "平雷之刻", "平雷之器", "平雷之冠" ]
  -
    id: 12
    maxRarity: 5
    mainName: "翠绿之影"
    subName: [ "野花记忆的绿野", "猎人青翠的箭羽", "翠绿猎人的笃定", "翠绿猎人的容器", "翠绿的猎人之冠" ]
  -
    id: 13
    maxRarity: 5
    mainName: "流浪大地的乐团"
    subName: [ "乐团的晨光", "琴师的箭羽", "终幕的时计", "吟游者之壶", "指挥的礼帽" ]
  -
    id: 14
    maxRarity: 4
    mainName: "勇者之心"
    subName: [ "勇士的勋章", "勇士的期许", "勇士的坚毅", "勇士的壮行", "勇士的冠冕" ]
  -
    id: 15
    maxRarity: 4
    mainName: "行者之心"
    subName: [ "故人之心", "归乡之羽", "逐光之石", "异国之盏", "感别之冠" ]
  -
    id: 16
    maxRarity: 4
    mainName: "武人"
    subName: [ "武人的红花", "武人的羽饰", "武人的水漏", "武人的酒杯", "武人的头巾" ]
  -
    id: 17
    maxRarity: 4
    mainName: "赌徒"
    subName: [ "赌徒的胸花", "赌徒的羽饰", "赌徒的怀表", "赌徒的骰盅", "赌徒的耳环" ]
  -
    id: 18
    maxRarity: 4
    mainName: "守护之心"
    subName: [ "守护之花", "守护徽印", "守护座钟", "守护之皿", "守护束带" ]
  -
    id: 19
    maxRarity: 4
    mainName: "学士"
    subName: [ "学士的书签", "学士的羽笔", "学士的时钟", "学士的墨杯", "学士的镜片" ]
  -
    id: 20
    maxRarity: 4
    mainName: "奇迹"
    subName: [ "奇迹之花", "奇迹之羽", "奇迹之沙", "奇迹之杯", "奇迹耳坠" ]
  -
    id: 21
    maxRarity: 4
    mainName: "教官"
    subName: [ "教官的胸花", "教官的羽饰", "教官的怀表", "教官的茶杯", "教官的帽子" ]
  -
    id: 22
    maxRarity: 4
    mainName: "血战之人"
    subName: [ "战狂的蔷薇", "战狂的翎羽", "战狂的时针", "战狂的骨杯", "战狂的鬼面" ]
  -
    id: 23
    maxRarity: 4
    mainName: "遗馈"
    subName: [ "流放者之花", "流放者之羽", "流放者怀表", "流放者之杯", "流放者头冠" ]

fiveRarity: [ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

domains:
  -
    id: 0
    name: "孤云凌霄之处"
    product: [ 0, 9, 14 ]
  -
    id: 1
    name: "芬德尼尔之顶"
    product: [ 1, 5, 17, 18 ]
  -
    id: 2
    name: "华池岩岫"
    product: [ 2, 8, 17, 19 ]
  -
    id: 3
    name: "无妄引咎迷宫"
    product: [ 3, 6, 16, 18 ]
  -
    id: 4
    name: "铭记之谷"
    product: [ 7, 2, 20 ]
  -
    id: 5
    name: "仲夏庭院"
    product: [ 10, 11, 15 ]
  -
    id: 6
    name: "世界BOSS挑战"
    product: [ 4, 13, 21, 22, 23 ]