aby:
  - ^深渊 +\d+$
  - ^上期深渊 +\d+$
artifacts:
  - ^圣遗物 +(\d+)$
  - ^圣遗物 *$
  - ^(强化|副本) *$
card:
  - ^米游社 *(\[CQ:at,qq=)?(\d*)$
character:
  - ^我的 +[\u4e00-\u9fa5]+$
gacha:
  - ^十连 *$
  - ^卡池 +(常驻|角色|武器)
tools:
  - ^roll *([+-]?\d+)?$
  - ^help *$
  - ^带个话 +.+$
  - ^管理 *$
master:
  - ^带话权限 +\d+ +(on|off)$
  - ^十连权限 +\d+ +(on|off)$
  - ^圣遗物权限 +\d+ +(on|off)$
  - ^UID权限 +\d+ +(on|off)$
  - ^角色信息权限 +\d+ +(on|off)$
  - ^刷新卡池 *$
material:
  - ^武器 *$
  - ^天赋 *$
  - ^周本 *$
menu:
  - ^菜单 *$
  - ^(今天)?吃什么 *$
music:
  - ^点歌 +.+$
  - ^音乐源 +.+$
overview:
  - ^(角色|武器) +[\u4e00-\u9fa5]+$
package:
  - ^UID +\d+$
quote:
  - ^伟大的升华 *$
save:
  - ^(绑定|改绑) +\d+$

