#card:
#  - ^#gq *(\[CQ:at,qq=)?([0-9]*)
#package:
#  - ^#uid *[0-9]+$
#save:
#  - ^#(s|c) *[0-9]+$
#character:
#  - ^#a *[\u4e00-\u9fa5]+$
#artifacts:
#  - ^#(r|i|d) *([0-9]?|[0-9a-fA-F]{16})$
#overview:
#  - ^#info *[\u4e00-\u9fa5]+$
#gacha:
#  - ^#w *$
#  - ^#t *(常驻|角色|武器)
#tools:
#  - ^.(r[0-9]+)?d[0-9]+$
#  - ^#help *$
#  - ^#repo *$
#  - ^#fb +.*
#  - ^#rhelp *$
#master:
#  - ^#fba *[0-9]+ *(on|off)$
#  - ^#wa *[0-9]+ *(on|off)$
#  - ^#ra *[0-9]+ *(on|off)$
#  - ^#qa *[0-9]+ *(on|off)$
#  - ^#ifa *[0-9]+ *(on|off)$
#  - ^#rw *$

card:
  - ^米游社 *(\[CQ:at,qq=)?(\d*)$
package:
  - ^UID +\d+$
save:
  - ^(绑定|改绑) +\d+$
character:
  - ^我的 +[\u4e00-\u9fa5]+$
artifacts:
  - ^圣遗物 +(\d+)$
  - ^圣遗物 *$
  - ^(强化|副本) *$
overview:
  - ^角色 +[\u4e00-\u9fa5]+$
gacha:
  - ^十连 *$
  - ^卡池 +(常驻|角色|武器)
tools:
  - ^roll *([+-]?\d+)?$
  - ^help *$
  - ^带个话 +.*
  - ^管理 *$
master:
  - ^带话权限 +\d+ +(on|off)$
  - ^十连权限 +\d+ +(on|off)$
  - ^圣遗物权限 +\d+ +(on|off)$
  - ^UID权限 +\d+ +(on|off)$
  - ^角色信息权限 +\d+ +(on|off)$
  - ^刷新卡池 *$
material:
  - ^武器 *$
  - ^天赋 *$
  - ^周本 *$
music:
  - ^点歌 +?.+$

