card:
  - ^#gq *(\[CQ:at,qq=)?([0-9]*)
package:
  - ^#uid *[0-9]+$
save:
  - ^#(s|c) *[0-9]+$
character:
  - ^#a *[\u4e00-\u9fa5]+$
help:
  - ^#help *$
  - ^#repo *$
artifacts:
  - ^#(r|i|d) *([0-9]?|[0-9a-fA-F]{16})$
gacha:
  - ^#w *$
  - ^#t *(常驻|角色|武器)
tools:
  - ^.(r[0-9]+)?d[0-9]+$