breakfast:
  # 地球菜单
  - 三明治
  - 包子
  - 南瓜饼
  - 叉烧包
  - 土司
  - 土豆饼
  - 小春饼
  - 小笼包
  - 年糕
  - 手抓饼
  - 曹粉
  - 松饼
  - 河粉
  - 油条
  - 燕麦
  - 牛奶
  - 玉米
  - 皮糕
  - 米粉
  - 糊糊
  - 糯米鸡
  - 肠粉
  - 荷包蛋
  - 葱油饼
  - 蛋酥卷
  - 豆浆
  - 面包
  - 饺子
  - 馄饨
  - 马蹄糕
  - 鸡蛋
  # 提瓦特菜单
  - 三彩团子
  - 什锦炒面
  - 凉拌薄荷
  - 庄园烤松饼
  - 摩拉肉
  - 月亮派
  - 杏仁豆腐
  - 渔人吐司
  - 满足沙拉
  - 炸萝卜丸子
  - 烤吃虎鱼
  - 爪爪土豆饼
  - 米窝窝
  - 绝云锅巴
  - 绯樱天妇罗
  - 绯樱饼
  - 莲子禽蛋羹
  - 莲花酥
  - 萝卜时疏汤
  - 蒙德土豆饼
  - 蒙德烤鱼
  - 蟹黄壳壳烧
  - 野菇鸡肉串
  - 鸟蛋烧
  - 鸡豆花
  - 黄油松茸

lunch:
  # 地球菜单
  - 凉皮
  - 刀削面
  - 北京烤鸭
  - 卤肉饭
  - 味增汤
  - 土豆粉
  - 寿司
  - 披萨
  - 拉面
  - 水煮鱼
  - 汉堡
  - 油泼面
  - 炒面
  - 炒饭
  - 炸酱面
  - 炸鸡
  - 烤肉饭
  - 烩面
  - 热干面
  - 煎饼果子
  - 牛排
  - 牛肉饭
  - 猪排
  - 生煎
  - 盖浇饭
  - 米线
  - 羊肉汤
  - 肉夹馍
  - 蒸包
  - 蒸排骨
  - 蛋包饭
  - 螺狮粉
  - 酸菜鱼
  - 酸辣粉
  - 重庆小面
  - 驴肉火烧
  - 鲱鱼罐头
  - 麦当劳
  - 麻辣烫
  - 麻辣香锅
  - 黄焖鸡米饭
  # 提瓦特菜单
  - 万民堂水煮鱼
  - 冷肉拼盘
  - 北地烟熏鸡
  - 北地苹果焖肉
  - 味增汤
  - 嘟嘟莲海鲜羹
  - 天枢肉
  - 山珍热卤面
  - 岩港三鲜
  - 市井杂煮
  - 干炒鱼河
  - 松茸肉卷
  - 松鼠鱼
  - 水煮黑背鲈
  - 火火肉酱面
  - 烤蘑菇披萨
  - 珍珠翡翠白玉汤
  - 甜甜花酿鸡
  - 白汁时疏烩肉
  - 稠汁蔬菜炖肉
  - 翡玉什锦袋
  - 腌笃鲜
  - 蜜酱胡萝卜煎肉
  - 蟹黄火腿焗时疏
  - 轻策农家菜
  - 风神杂烩菜
  - 香嫩椒椒鸡
  - 鲜虾脆薯盏
  - 黄金蟹

dinner:
  # 地球菜单
  - 刀削面
  - 卤肉饭
  - 土豆粉
  - 寿司
  - 披萨
  - 拉面
  - 排骨
  - 水煮鱼
  - 汉堡
  - 油泼面
  - 炒面
  - 炒饭
  - 炸酱面
  - 炸鸡
  - 炸鸡
  - 烤肉饭
  - 烤鸭
  - 烩面
  - 热干面
  - 煎饼果子
  - 牛排
  - 牛肉饭
  - 生煎
  - 盖浇饭
  - 米线
  - 羊肉汤
  - 肉夹馍
  - 蒸包
  - 蛋包饭
  - 螺狮粉
  - 酸菜鱼
  - 酸辣粉
  - 重庆小面
  - 驴肉火烧
  - 麻辣烫
  - 麻辣香锅
  - 黄焖鸡米饭
  # 提瓦特菜单
  - 万民堂水煮鱼
  - 仙跳墙
  - 兽肉薄荷卷
  - 兽骨拉面
  - 冷肉拼盘
  - 北地烟熏鸡
  - 北地苹果焖肉
  - 味增汤
  - 嘟嘟莲海鲜羹
  - 大黄金吮指鸡
  - 天枢肉
  - 山珍热卤面
  - 岩港三鲜
  - 市井杂煮
  - 干烧香鱼
  - 提神醒脑披萨
  - 松茸肉卷
  - 松鼠鱼
  - 水煮黑背鲈
  - 渡来禽肉
  - 火火肉酱面
  - 烤蘑菇披萨
  - 珍珠翡翠白玉汤
  - 甜甜花酿鸡
  - 白汁时疏烩肉
  - 稠汁蔬菜炖肉
  - 素鲍鱼
  - 翡玉什锦袋
  - 腌笃鲜
  - 蜜酱胡萝卜煎肉
  - 蟹黄火腿焗时疏
  - 蟹黄豆腐
  - 轻策农家菜
  - 金枪鱼寿司
  - 风神杂烩菜
  - 香嫩椒椒鸡
  - 黄油煎鱼
  - 黄金蟹
