breakfast:
  - 包子
  - 油条
  - 燕麦
  - 牛奶
  - 粥
  - 糊糊
  - 豆浆
  - 面包
  - 馄饨
  - 鸡蛋

lunch:
  - 凉皮
  - 刀削面
  - 卤肉饭
  - 土豆粉
  - 寿司
  - 小笼包
  - 披萨
  - 拉面
  - 水煮鱼
  - 汉堡
  - 油泼面
  - 炒面
  - 炒饭
  - 炸酱面
  - 炸鸡
  - 蒸包
  - 烤肉饭
  - 烩面
  - 热干面
  - 煎饼果子
  - 生煎
  - 盖浇饭
  - 米线
  - 羊肉汤
  - 肉夹馍
  - 螺狮粉
  - 酸菜鱼
  - 酸辣粉
  - 重庆小面
  - 驴肉火烧
  - 麻辣烫
  - 麻辣香锅
  - 黄焖鸡米饭

dinner:
  - 刀削面
  - 卤肉饭
  - 土豆粉
  - 寿司
  - 披萨
  - 拉面
  - 水煮鱼
  - 汉堡
  - 油泼面
  - 火锅
  - 炒面
  - 炒饭
  - 炸酱面
  - 炸鸡
  - 蒸包
  - 烤串
  - 烤肉饭
  - 烤鸭
  - 烩面
  - 热干面
  - 煎饼果子
  - 盖浇饭
  - 米线
  - 羊肉汤
  - 螺狮粉
  - 酸菜鱼
  - 酸辣粉
  - 重庆小面
  - 驴肉火烧
  - 麻辣烫
  - 麻辣香锅
  - 黄焖鸡米饭

