breakfast:
  - 粥系列
  - 面系列
  - 曹粉
  - 炒饭
  - 披萨
  - 饺子
  - 油条
  - 燕麦
  - 酸奶
  - 奶酪
  - 牛奶
  - 糊糊
  - 豆浆
  - 面包
  - 馒头
  - 馄饨
  - 鸡蛋
  - 肠粉
  - 肉包
  - 松饼
  - 玉米
  - 椰奶
  - 土司
  - 红茶
  - 绿茶
  - 黄茶
  - 白茶
  - 咖啡
  - 腰果
  - 年糕
  - 泡面
  - 皮糕
  - 蛋酥卷
  - 马蹄糕
  - 烙烫面
  - 小春饼
  - 糯米鸡
  - 油炸鬼
  - 火腿蛋
  - 溏心蛋
  - 荷包蛋
  - 三明治
  - 叉烧包  
  - 手抓饼  
  - 炒米粉
  - 炒河粉
  - 汤米粉
  - 汤河粉
  - 黑芝麻
  - 土豆饼
  - 南瓜饼
  - 小米米浆
  - 胡萝卜汁
  - 意大利面
  - 小丸子汤
  - 香酥葱油薄饼
  - 泡面＋板蓝根
lunch:
  - 凉皮
  - 刀削面
  - 卤肉饭
  - 土豆粉
  - 寿司
  - 小笼包
  - 披萨
  - 拉面
  - 水煮鱼
  - 汉堡
  - 油泼面
  - 炒面
  - 炒饭
  - 炸酱面
  - 炸鸡
  - 蒸包
  - 烤肉饭
  - 烩面
  - 热干面
  - 煎饼果子
  - 生煎
  - 盖浇饭
  - 米线
  - 羊肉汤
  - 肉夹馍
  - 螺狮粉
  - 酸菜鱼
  - 酸辣粉
  - 重庆小面
  - 驴肉火烧
  - 麻辣烫
  - 麻辣香锅
  - 黄焖鸡米饭

dinner:
  - 刀削面
  - 卤肉饭
  - 土豆粉
  - 寿司
  - 披萨
  - 拉面
  - 水煮鱼
  - 汉堡
  - 油泼面
  - 火锅
  - 炒面
  - 炒饭
  - 炸酱面
  - 炸鸡
  - 蒸包
  - 烤串
  - 烤肉饭
  - 烤鸭
  - 烩面
  - 热干面
  - 煎饼果子
  - 盖浇饭
  - 米线
  - 羊肉汤
  - 螺狮粉
  - 酸菜鱼
  - 酸辣粉
  - 重庆小面
  - 驴肉火烧
  - 麻辣烫
  - 麻辣香锅
  - 黄焖鸡米饭

