starFive:
  up: 
    - 达达利亚
  nonUp: 
    - 刻晴
    - 莫娜
    - 七七
    - 迪卢克
    - 琴

starFour:
  up:
    - 罗莎莉亚
    - 菲谢尔
    - 芭芭拉
    
  nonUp:
    - 砂糖
    - 辛焱
    - 迪奥娜
    - 重云
    - 诺艾尔
    - 班尼特
    - 凝光
    - 行秋
    - 北斗
    - 香菱
    - 雷泽
