name: Code check

on:
  push:
    branches:
      - dev
      - master

jobs:
  resources_update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node modules
        run: npm install
      - name: Check code
        id: check-code
        run: |
          result=$(npm run --silent check || :)
          result="${result//'%'/'%25'}"
          result="${result//$'\n'/'%0A'}"
          result="${result//$'\r'/'%0D'}"
          echo ::set-output name=result::"$result"
      - name: Comment if check failed
        uses: peter-evans/commit-comment@v1
        if: ${{ '' != steps.check-code.outputs.result }}
        with:
          body: "```${{ steps.get-comment-body.outputs.body }}'%0A'```"
      - name: Error if check failed
        if: ${{ '' != steps.check-code.outputs.result }}
        run: exit -1
