on:
  push:
    branches:
      - dev
  schedule:
    # UTC
    - cron: "0 20 * * *"

jobs:
  resources_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          ./resources/update.sh

          if [[ -n $(git status --porcelain) ]]
          then
            git config user.name 'github-actions'
            git config user.email 'github-actions@github.com'
            git add .
            git commit -m 'update resources'
            git push
          fi
